### ISSUE TITLE
Crash in specific action

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#78] opened 2024-02-19 18:13 UTC
Primal always crash if I:

Go to messages window, click in in the button to wtite a new message, then click on android back button two times, one to close keyboard and other to go back to messages window. Then click on home button. Primal will crash. See the video:

https://github.com/PrimalHQ/primal-android-app/assets/1178856/998cacc9-dc34-490b-a285-49501eb9da21

**Comment by AleksandarIlic** [comment] 2024-02-27 13:09
Is there are way for you to catch the crash log (stacktrace)? If not, I could create a special build which will send the crash log to our server.

**Comment by bitcoinuser** [comment] 2024-02-27 14:22
> Is there are way for you to catch the crash log (stacktrace)? If not, I could create a special build which will send the crash log to our server.

There were crashs that I was able to send to your server.

**Comment by AleksandarIlic** [comment] 2024-02-27 14:38
That's probably Google Play dialog popping up. I fixed some crashes, but not all since not all logs get deobfuscated for some reason.

If you can reproduce this crash easily, I can add you temporarily to our internal alpha track so you could install the latest alpha build and verify if it's fixed or still crashing.

**Comment by bitcoinuser** [comment] 2024-02-27 14:41
> Is there are way for you to catch the crash log (stacktrace)? If not, I could create a special build which will send the crash log to our server.

Ok, send me the build.

**Comment by AleksandarIlic** [comment] 2024-02-27 14:56
aosp apk: https://drive.google.com/file/d/1fWIaArmM773kIdsih3qzFOxaT_HgVSui/view?usp=drive_link

google apk: https://drive.google.com/file/d/1RX4IaX4oMFjPRXoVSiYzso2ZPKx7H_Gg/view?usp=drive_link

Crash log is automatically upload as soon as the app force closes. Let me know when you crash it.

**Comment by AleksandarIlic** [comment] 2024-02-27 15:26
There is nothing in the logs. If it didn't closed then there was no crash. On your video when you clicked Back there were no recommended users - that might be related. Or maybe the crash was fixed (since I can't tell which one was from you).

The black/white window is navigation bottom bar issue which we plan to fix with the nav bar rework soon.

**Comment by bitcoinuser** [comment] 2024-02-27 15:28
> There is nothing in the logs. If it didn't closed then there was no crash. On your video when you clicked Back there were no recommended users - that might be related. Or maybe the crash was fixed (since I can't tell which one was from you).
> 
> The black/white window is navigation bottom bar issue which we plan to fix with the nav bar rework soon.

I will keep still testing. I had crashs in the past, maybe I can reproduce again.

**Comment by bitcoinuser** [comment] 2024-02-27 15:30
I had a crash now, but was doing other thing. Did you receive any logs?

**Comment by AleksandarIlic** [comment] 2024-02-27 15:36
Unfortunately no, I just learned that the endpoint for receiving logs is down for some reason. I'm waiting on the backend to fix this. I'll let you know when it's up again.

**Comment by AleksandarIlic** [comment] 2024-02-27 23:03
@bitcoinuser The endpoint has been fixed on the backend - future crash logs will be coming through now.

**Comment by bitcoinuser** [comment] 2024-02-27 23:36
> @bitcoinuser The endpoint has been fixed on the backend - future crash logs will be coming through now.

Ok, I had a new crash, did you receive something?

**Comment by AleksandarIlic** [comment] 2024-02-27 23:41
I got the logs. Thanks!

**Comment by AleksandarIlic** [comment] 2024-02-28 13:17
@bitcoinuser here is the new build with fixes:
aosp release: https://drive.google.com/file/d/19BWV4ZIE7XccERAPbLyYgeqx-zFTOjOm/view?usp=sharing
google release: https://drive.google.com/file/d/1DFB_sDhRIHqOy86chwsy87GPb_5Ukt6V/view?usp=sharing

Builds have crash reporting enabled.

And could you please check how the feed is working? I have upgraded the libraries to the last version (after 2 months) so scrolling glitches might have been fixed by the platform.

**Comment by bitcoinuser** [comment] 2024-02-28 13:56
Hi, I updated, the app crashed two times and I think the feed is worst in this version, "freezing more"

**Comment by bitcoinuser** [comment] 2024-02-28 13:57
> Hi, I updated, the app crashed two times and I think the feed is worst in this version, "freezing more"


https://github.com/PrimalHQ/primal-android-app/assets/1178856/131a5ef0-e9a0-4a8b-a2c5-81d744413392

**Comment by bitcoinuser** [comment] 2024-02-28 13:58
> > Hi, I updated, the app crashed two times and I think the feed is worst in this version, "freezing more"
> 
>  Screenrecorder-2024-02-28-10-56-42-954.mp4

This is when I scroll down and click home button to automatically go to top

**Comment by AleksandarIlic** [comment] 2024-02-28 15:27
Thanks, I got the logs. Yesterday we had two unique crash logs, now it's just one. We are getting closer.

This is strange for the feed, because I'm noticing actually a small performance improvements and better scrolling gesture handling on my device. Could you tell me again which device are you using and which OS version?

**Comment by bitcoinuser** [comment] 2024-02-28 15:34
> Thanks, I got the logs. Yesterday we had two unique crash logs, now it's just one. We are getting closer.
> 
> This is strange for the feed, because I'm noticing actually a small performance improvements and better scrolling gesture handling on my device. Could you tell me again which device are you using and which OS version?

Redmi note 9s

![Screenshot_2024-02-28-12-34-07-378_com android settings](https://github.com/PrimalHQ/primal-android-app/assets/1178856/eb419ac3-ec93-476a-859f-6aaca4d054c1)

**Comment by bitcoinuser** [comment] 2024-02-28 15:43
> > Thanks, I got the logs. Yesterday we had two unique crash logs, now it's just one. We are getting closer.
> > This is strange for the feed, because I'm noticing actually a small performance improvements and better scrolling gesture handling on my device. Could you tell me again which device are you using and which OS version?
> 
> Redmi note 9s
> 
> ![Screenshot_2024-02-28-12-34-07-378_com android settings](https://private-user-images.githubusercontent.com/1178856/308611459-eb419ac3-ec93-476a-859f-6aaca4d054c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQ3OTQsIm5iZiI6MTcwOTEzNDQ5NCwicGF0aCI6Ii8xMTc4ODU2LzMwODYxMTQ1OS1lYjQxOWFjMy1lYzkzLTQ3NmEtODU5Zi02YWFjYTRkMDU0YzEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMTUzNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE3MTliNzVkODA1OWQ0MjU5OWE1MjQ3MzJmMTY0ZmI2MjAyYjhiYWMwNDczOWUxMGMwOTFhZDU5OTUwMzBiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dWRDSuLCOkHVF1k3i9n6kj5JaUSlHtJk0E4ewEIZdY0)

Maybe better ignore my comment of slow. I think it's working ok.

**Comment by bitcoinuser** [comment] 2024-02-28 15:46
> > > Thanks, I got the logs. Yesterday we had two unique crash logs, now it's just one. We are getting closer.
> > > This is strange for the feed, because I'm noticing actually a small performance improvements and better scrolling gesture handling on my device. Could you tell me again which device are you using and which OS version?
> > 
> > 
> > Redmi note 9s
> > ![Screenshot_2024-02-28-12-34-07-378_com android settings](https://private-user-images.githubusercontent.com/1178856/308611459-eb419ac3-ec93-476a-859f-6aaca4d054c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQ3OTQsIm5iZiI6MTcwOTEzNDQ5NCwicGF0aCI6Ii8xMTc4ODU2LzMwODYxMTQ1OS1lYjQxOWFjMy1lYzkzLTQ3NmEtODU5Zi02YWFjYTRkMDU0YzEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMTUzNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE3MTliNzVkODA1OWQ0MjU5OWE1MjQ3MzJmMTY0ZmI2MjAyYjhiYWMwNDczOWUxMGMwOTFhZDU5OTUwMzBiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dWRDSuLCOkHVF1k3i9n6kj5JaUSlHtJk0E4ewEIZdY0)
> 
> Maybe better ignore my comment of slow. I think it's working ok.

I think what is slow is the thing that hide and show the bottom and top bar. When I let the bottom and top bar fixed, works better.

**Comment by bitcoinuser** [comment] 2024-02-28 15:52
Sorry, I think is slower. Haha

**Comment by bitcoinuser** [comment] 2024-02-28 16:24
Ignore again, haha. Looks like after sometime using, it's faster.

**Closed** 2024-02-28 19:37 UTC
Labels: bug

**Comment by AleksandarIlic** [comment] 2024-02-29 00:32
There were two crashes. I have fixed one, but not yet other. I'll continue investigating no matter if the ticket is open or closed. Thanks for the help!

**Comment by AleksandarIlic** [comment] 2024-02-29 12:04
@bitcoinuser Here are the new 0.95.3 builds. 

aosp: https://drive.google.com/file/d/1iAl60MxTYYTLErM2PsQcCCS5LUxUH2uo/view?usp=sharing
google: https://drive.google.com/file/d/1HNRCpqvbutohNTIAi31KUl7dcWrs-sgO/view?usp=sharing

I wasn't able to reproduce, so not sure if it's really fixed.

**Comment by bitcoinuser** [comment] 2024-02-29 12:09
I will test

**Comment by AleksandarIlic** [comment] 2024-02-29 12:43
I got it. It wasnt fixed, damn. The stacktrace doesnt tell where the problem is.

Do you notice any pattern in app use before it crashes? Something that might give me a hint where to look.

**Comment by bitcoinuser** [comment] 2024-02-29 14:28
> Do you notice any pattern in app use before it crashes?

Switch between bottom buttons in a fast way. But it's not reproducible all times.

**Comment by bitcoinuser** [comment] 2024-03-01 00:03
> > Do you notice any pattern in app use before it crashes?
> 
> Switch between bottom buttons in a fast way. But it's not reproducible all times.

I could reproduce many times just alternating between notification and home buttons quickly. If you do this action for about one minute, I'm sure Primal will crash

**Comment by bitcoinuser** [comment] 2024-03-01 00:19
> > > Do you notice any pattern in app use before it crashes?
> > 
> > 
> > Switch between bottom buttons in a fast way. But it's not reproducible all times.
> 
> I could reproduce many times just alternating between notification and home buttons quickly. If you do this action for about one minute, I'm sure Primal will crash

And looks like happens more when the new notes bubble appear in home feed.

**Comment by AleksandarIlic** [comment] 2024-03-01 23:19
Thanks. This was helpful.

I found the cause. You just need to switch between notifications and any other tab and it will crash after 10+ switches approx. 

I'll do the fix first thing on Monday and we'll probably push that build as a public release.

**Comment by bitcoinuser** [comment] 2024-03-01 23:21
> Thanks. This was helpful.
> 
> I found the cause. You just need to switch between notifications and any other tab and it will crash after 10+ switches approx.
> 
> I'll do the fix first thing on Monday and we'll probably push that build as a public release.

Great. Primal will be a great client. So excited to see how this will develop.

**Comment by AleksandarIlic** [comment] 2024-03-04 16:57
New release 0.95.4 has been just published. You can check it out, there shouldn't be any crashes.

**Comment by bitcoinuser** [comment] 2024-03-04 17:03
> New release 0.95.4 has been just published. You can check it out, there shouldn't be any crashes.

Hi, will uninstall and install from playstore. Thanks
